version: "3.8"

services:
  doc_qa_frontend:
    container_name: doc_qa_react
    image: node:16-bullseye
    tty: true
    working_dir: /app
    ports:
      - 3000:8080
    volumes:
      - ./frontend:/app
    links:
      - doc_qa_backend

  doc_qa_backend:
    container_name: doc_qa_fastapi
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./backend:/app
